### ISSUE TITLE
Can't build the package through Rstudio Build & Reload

### ISSUE THREAD

**Issue by aushaff** [KIT-IfGG/LandClimTools#15] opened 2018-02-08 14:29 UTC
==> R CMD INSTALL --no-multiarch --with-keep.source LandClimTools

* installing to library ‘/home/austin/lib/R/library’
* installing *source* package ‘LandClimTools’ ...
** R
** inst
** preparing package for lazy loading
  |.................................................................| 100%
   inline R code fragments

processing file: vignette/Reference_Manual_LandClimTools.md
[1] "This is an old function. Use plot_gradient instead."

Quitting from lines 2-989 (vignette/Reference_Manual_LandClimTools.md) 
Error in vapply(x, format_sci_one, character(1L), ..., USE.NAMES = FALSE) : 
  values must be length 1,
 but FUN(X[[5]]) result is length 9
Error : unable to load R code in package ‘LandClimTools’
ERROR: lazy loading failed for package ‘LandClimTools’
* removing ‘/home/austin/lib/R/library/LandClimTools’
* restoring previous ‘/home/austin/lib/R/library/LandClimTools’

Exited with status 1.

**Comment by aushaff** [comment] 2018-02-08 14:44
This was resolved by deleting the vignette folder and R/manual.R

**Comment by floscher** [comment] 2018-02-08 15:52
Maybe this also caused this build to fail: https://travis-ci.org/floscher/LandClimTools/jobs/338751562

But on my machine the same commit was built flawlessly. Could it be that a new dependency is needed when the `vignette/` directory is present?

**Comment by KDolos** [comment] 2018-02-09 08:44
Yes, we solve that. I added these files to have an overview of all R-functions in the paclage for the landclim meeting in Feb. I moved this part to the "additional_files" folder, which I added to Rbiuldignore. I am not sure, if I added that the right way. On my computer is worked...
Sorry, but I guess in the beginning we will have to deal with some issues of my coding, because I used it only fo rmyself and my students, thus there are some "special features" we have to fix and which do not happen on my laptop.

**Comment by floscher** [comment] 2018-02-09 12:42
I can confirm this is now fixed: https://travis-ci.org/floscher/LandClimTools/builds/339383165

---

Do you know that the command
```bash
R CMD check LandClimTools_1.0.0.tar.gz
```
produces a similar [manual as PDF](https://github.com/KIT-IfGG/LandClimTools/files/1710958/LandClimTools-manual.pdf)?

If you'd set up Travis CI, the PDF manual and the `*.tar.gz` package would be automatically published on GitHub for every release. See https://github.com/floscher/LandClimTools/releases/tag/v1.0.0 for how that would look like.
I could help setting that up, but the essential steps have to be carried out by an administrator of this repository (i.e. you :wink:).

**Closed** 2018-03-02 17:17 UTC
